config/routes.rb
Rails.application.routes.draw do
  get 'public/top'
  get 'public/about'
  namespace :admin do
    get 'genres/index'
    get 'genres/edit'
  end
  get 'genres/index'
  get 'genres/edit'


  namespace :admin do
    resources :items
    resources :customers
    resources :orders, except: [:index] do#今回の使用はトップページを注文一覧とするためindexを除外
      resources :order_details, only: [:update]
    end
    resources :genres
    root :to => "homes#top"
  end

  scope module: :public do

    root :to => "homes#top"
    get 'home/about' => 'homes#about', as: 'about'


    resources :addresses
    resources :items
    get 'genres/:id' => 'items#genre', as: 'genre'
    get 'orders/thanks' => 'orders#thanks'
    post 'orders/confirm' => 'orders#confirm'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :orders
    resources :cart_items
    resources :customer
    resources :customers, only: [:update] do
      collection do                                           # resourcesで定義されるアクション以外を追加する(URIにidを挟まない場合はcollection)
        get "quit"                                            # quitのルーティング
        get "mypage" => 'customers#show'                      # mypageのルーティング
        get "edit" => "customers#edit"
      end
      member do                                               # resourcesで定義されるアクション以外を追加する(URIにidを挟む場合はmember)
        patch "withdraw" => "customers#withdraw"              # 論理削除用のルーティング
      end
    end

  end

# 顧客用
# # URL /customers/sign_in ...
 devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
 devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
    # get 'addresses/inidex'
    # get 'addresses/edit'


  # namespace :public do
  #   get 'items/index'
  #   get 'items/show'

  # end
  # namespace :public do
  #   get 'orders/new'
  #   get 'orders/thanks'
  #   get 'orders/index'
  #   get 'orders/show'
  # end
  # namespace :public do
  #   get 'cart_items/index'
  # end
  # namespace :public do
  #   get 'customers/show'
  #   get 'customers/quit'
  #   get 'customers/edit'
  # end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :post_code, presence: true, length: { is: 7 }, numericality: true
  validates :address, presence: true
  validates :name, presence: true

  def post_code_in_address
    "〒" + post_code + "  " + address
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  def add_tax_cost
    (cost * 1.10).round
  end
  
  def subtotal
    item.add_tax_cost * amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :cart_items, dependent: :destroy
  # has_many :items, through: :cart_items (← customerでitemの情報を使いたいとき)
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true, uniqueness: true

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  belongs_to :genre

  validates :genre_id, presence: true
  validates :cost, presence: true
  validates :explanation, presence: true
  validates :name, presence: true
  # validates :image, presence: true

  has_one_attached :image

  def add_tax_cost
    (cost * 1.10).round
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer

  enum payment_method: {credit_card: 0, transfer: 1}
  enum address_type: { self_address: 0, registered_address: 1, new_address: 2}
	enum status: {wait_payment: 0, confirm_payment: 1, maiking: 2, prepar_shipping: 3, finish_prepar: 4}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum production_status: {unable_to_start: 0, waiting_for_production: 1, in_production: 2,  production_completed: 3}

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
   before_action :authenticate_admin!
  def top
    @order = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.all
    # @cake_genre = Genre.name(params[:id])
  end

  def new
    @item = Item.new
    # @genres = Genre.all
    # @genre = Genre.new
    # jenre_selection = @genre.(name)

    # @select_genre_array = []
    # select_genre_array.each_with_index do |genre_name, i|

    # end
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @item =Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
      flash[:notice] = 'The product has been registered'
    else
      @genres = Genre.all
      flash.now[:alert] = 'Could not register product'
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
      if @item.update(item_params)
       redirect_to admin_item_path(@item.id)
       flash[:notice] = 'Product updated'
      else
        @genres = Genre.all
        flash.now[:alert] = 'Could not update product'
        render  :edit
      end
  end

  private

  def item_params
    params.require(:item).permit(:name, :explanation, :cost, :image, :is_sales, :genre_id)
  end


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
before_action :authenticate_admin!

  def customer_index
    @customer = Customer.find(params[:id])
    @orders = @customer.orders.all
  end

  def show
    @order = Order.find(params[:id])
    # @customer = Customer.find(params[:id])
    @order_details = @order.order_details
    @postage = 800
    @subtotal = @order.total_payment - @postage
  end

  def update
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
    @order.update(order_params)

    if @order.status == "confirm_payment"
       @order_details.update(production_status:'waiting_for_production')
    end

    redirect_to request.referer

  end


  private

  def order_params
    params.require(:order).permit(:status)
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# before_action :authenticate_user!, except: [:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :telephone_number])
  end

  private

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
      # adminユーザー
      admin_root_path

    else
      # customerユーザー
      mypage_customers_path
    end
  end
  
  # def after_sign_in_path_for(resource_or_scope)
  #   root_path
  # end

  def after_sign_out_path_for(resource_or_scope) # adminかそれ以外かでサインアウトした後の遷移先画面を分岐させる
    if resource_or_scope == :admin
      new_admin_session_path

    else
      about_path

    end
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/orders/index.html.erb
<h1>Admin::Orders#index</h1>
<p>Find me in app/views/admin/orders/index.html.erb</p>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="col-7">
      <h4>注文履歴</h4>
      <%= form_with model: @order, url: admin_order_path, method: :patch, local: true do |f| %>
      <table class="table">
        <tr><th>購入者</th><td><%= @order.name %></td></tr>
        <tr><th>注文日</th><td><%= @order.created_at.strftime("%Y/%m/%d") %></td></tr>
        <tr><th>配送先</th><td><%= "〒"+  @order.post_code + "  " + @order.address %><br><%= @order.name %></td></tr>
        <tr><th>支払方法</th><td><%= @order.payment_method_i18n %></td></tr>
        <tr>
          <th>注文ステータス</th>
          <td>
            <%= f.select :status, Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]} %>
            <%= f.submit "更新" , class:"btn btn-success" %>
          </td>
        </tr>
      </table>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-7">
      <table class="table">
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
        <tbody>
           <% @order_details.each do |order_detail| %>
             <tr>
               <td><%= order_detail.item.name %></td>
               <td><%= order_detail.item.add_tax_cost %></td>
               <td><%= order_detail.quantity %></td>
               <td><%= @subtotal.to_s(:delimited) %></td>
               <td>
                 <%= form_with model: [@order,order_detail], url: admin_order_order_detail_path(@order,order_detail), method: :patch, local: true do |f| %>
                   <%= f.select :production_status, OrderDetail.production_statuses.keys.map {|k| [I18n.t("enums.order_detail.production_status.#{k}"), k]} %>
                   <%= f.submit "更新" , class:"btn btn-success" %>
                 <% end %>
               </td>
             </tr>
           <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-4 d-flex align-items-end mb-4 ml-4">
      <table>
        <tr><th class="pr-2">商品合計</th><td><%= "#{@subtotal.to_s(:delimited)}" + "円" %></td></tr>
        <tr><th class="pr-2">送料</th><td><%= "#{@postage}" + "円" %></td></tr>
        <tr><th class="pr-2">請求金額合計</th><td><%= "#{@order.total_payment.to_s(:delimited)}" + "円" %></td></tr>
      </table>
    </div>
  </div>

</div>