config/routes.rb
Rails.application.routes.draw do
  get 'public/top'
  get 'public/about'
  namespace :admin do
    get 'genres/index'
    get 'genres/edit'
  end
  get 'genres/index'
  get 'genres/edit'


  namespace :admin do
    resources :items
    resources :customers
    resources :orders, except: [:index] do#今回の使用はトップページを注文一覧とするためindexを除外
      resources :order_details, only: [:update]
    end
    resources :genres
    root :to => "homes#top"
  end

  scope module: :public do

    root :to => "homes#top"
    get 'home/about' => 'homes#about', as: 'about'


    resources :addresses
    resources :items
    get 'genres/:id' => 'items#genre', as: 'genre'
    get 'orders/thanks' => 'orders#thanks'
    post 'orders/confirm' => 'orders#confirm'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :orders
    resources :cart_items
    resources :customer
    resources :customers, only: [:update] do
      collection do                                           # resourcesで定義されるアクション以外を追加する(URIにidを挟まない場合はcollection)
        get "quit"                                            # quitのルーティング
        get "mypage" => 'customers#show'                      # mypageのルーティング
        get "edit" => "customers#edit"
      end
      member do                                               # resourcesで定義されるアクション以外を追加する(URIにidを挟む場合はmember)
        patch "withdraw" => "customers#withdraw"              # 論理削除用のルーティング
      end
    end

  end

# 顧客用
# # URL /customers/sign_in ...
 devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
 devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
    # get 'addresses/inidex'
    # get 'addresses/edit'


  # namespace :public do
  #   get 'items/index'
  #   get 'items/show'

  # end
  # namespace :public do
  #   get 'orders/new'
  #   get 'orders/thanks'
  #   get 'orders/index'
  #   get 'orders/show'
  # end
  # namespace :public do
  #   get 'cart_items/index'
  # end
  # namespace :public do
  #   get 'customers/show'
  #   get 'customers/quit'
  #   get 'customers/edit'
  # end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true, uniqueness: true

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
before_action :authenticate_admin!

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def new
    @genre = Genre.new(genre_params)
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash.now[notice] = "新規登録しました"
      redirect_to admin_genres_path
    else
      flash.now[alert] = "ジャンルが重複していないか確認してください"
      @genres = Genre.all
      render :index
    end
  end

  def destroy
    genre = Genre.find(params[:id])
    genre.destroy
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if  @genre.update(genre_params)
      flash.now[notice] = "編集に成功しました"
      redirect_to admin_genres_path
    else
      flash.now[alert] = "編集に失敗しました"
      @genres = Genre.all
      render :index
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/admin/genres/_form.html.erb
<%= form_with model: genre, url: admin_genres_path, method: :post do |f| %>
<table>
    <tr>
        <td><%= f.label :name, "ジャンル名" %></td>
        <td><%= f.text_field :name, placeholder: "ジャンル名" %></td>
        <td><%= f.submit '新規登録', class: "btn btn-primary" %></td>
    </tr>
</table>

<% end %>

app/views/admin/genres/edit.html.erb
<h4>ジャンル編集</h4>

<%= form_with model: @genre, url: admin_genre_path(@genre.id), method: :patch do |f| %>

<table>
    <tr>
        <td><%= f.label :name, "ジャンル名" %></td><td><%= f.text_field :name %></td>
        <td><%= f.submit '変更内容を保存する', class: "btn btn-success" %></td>
    </tr>
</table>
<% end %>

<%= link_to "戻る", admin_genres_path, class: "btn btn-primary" %>

app/views/admin/genres/index.html.erb
<h4>ジャンル追加/一覧</h4>

<%= render 'form', genre: @genre %>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">ジャンル</th>
    </tr>
  </thead>
  <tbody>
     <% @genres.each do |genre| %>
    <tr>
      <td><%= genre.name %></td>
      <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success"  %>
      <%= link_to "削除する", admin_genre_path(genre.id), method: :delete, data: {confirm: "削除しますか？"}, class: "btn btn-danger"%></td>
    </tr>
    <% end %>
  </tbody>
</table>