config/routes.rb
Rails.application.routes.draw do
  get 'public/top'
  get 'public/about'
  namespace :admin do
    get 'genres/index'
    get 'genres/edit'
  end
  get 'genres/index'
  get 'genres/edit'


  namespace :admin do
    resources :items
    resources :customers
    resources :orders, except: [:index] do#今回の使用はトップページを注文一覧とするためindexを除外
      resources :order_details, only: [:update]
    end
    resources :genres
    root :to => "homes#top"
  end

  scope module: :public do

    root :to => "homes#top"
    get 'home/about' => 'homes#about', as: 'about'


    resources :addresses
    resources :items
    get 'genres/:id' => 'items#genre', as: 'genre'
    get 'orders/thanks' => 'orders#thanks'
    post 'orders/confirm' => 'orders#confirm'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :orders
    resources :cart_items
    resources :customer
    resources :customers, only: [:update] do
      collection do                                           # resourcesで定義されるアクション以外を追加する(URIにidを挟まない場合はcollection)
        get "quit"                                            # quitのルーティング
        get "mypage" => 'customers#show'                      # mypageのルーティング
        get "edit" => "customers#edit"
      end
      member do                                               # resourcesで定義されるアクション以外を追加する(URIにidを挟む場合はmember)
        patch "withdraw" => "customers#withdraw"              # 論理削除用のルーティング
      end
    end

  end

# 顧客用
# # URL /customers/sign_in ...
 devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
 devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
    # get 'addresses/inidex'
    # get 'addresses/edit'


  # namespace :public do
  #   get 'items/index'
  #   get 'items/show'

  # end
  # namespace :public do
  #   get 'orders/new'
  #   get 'orders/thanks'
  #   get 'orders/index'
  #   get 'orders/show'
  # end
  # namespace :public do
  #   get 'cart_items/index'
  # end
  # namespace :public do
  #   get 'customers/show'
  #   get 'customers/quit'
  #   get 'customers/edit'
  # end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :post_code, presence: true, length: { is: 7 }, numericality: true
  validates :address, presence: true
  validates :name, presence: true

  def post_code_in_address
    "〒" + post_code + "  " + address
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  def add_tax_cost
    (cost * 1.10).round
  end
  
  def subtotal
    item.add_tax_cost * amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :cart_items, dependent: :destroy
  # has_many :items, through: :cart_items (← customerでitemの情報を使いたいとき)
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true, uniqueness: true

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  belongs_to :genre

  validates :genre_id, presence: true
  validates :cost, presence: true
  validates :explanation, presence: true
  validates :name, presence: true
  # validates :image, presence: true

  has_one_attached :image

  def add_tax_cost
    (cost * 1.10).round
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer

  enum payment_method: {credit_card: 0, transfer: 1}
  enum address_type: { self_address: 0, registered_address: 1, new_address: 2}
	enum status: {wait_payment: 0, confirm_payment: 1, maiking: 2, prepar_shipping: 3, finish_prepar: 4}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum production_status: {unable_to_start: 0, waiting_for_production: 1, in_production: 2,  production_completed: 3}

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
before_action :authenticate_admin!

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def new
    @genre = Genre.new(genre_params)
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash.now[notice] = "新規登録しました"
      redirect_to admin_genres_path
    else
      flash.now[alert] = "ジャンルが重複していないか確認してください"
      @genres = Genre.all
      render :index
    end
  end

  def destroy
    genre = Genre.find(params[:id])
    genre.destroy
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if  @genre.update(genre_params)
      flash.now[notice] = "編集に成功しました"
      redirect_to admin_genres_path
    else
      flash.now[alert] = "編集に失敗しました"
      @genres = Genre.all
      render :index
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
   before_action :authenticate_admin!
  def top
    @order = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.all
    # @cake_genre = Genre.name(params[:id])
  end

  def new
    @item = Item.new
    # @genres = Genre.all
    # @genre = Genre.new
    # jenre_selection = @genre.(name)

    # @select_genre_array = []
    # select_genre_array.each_with_index do |genre_name, i|

    # end
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @item =Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
      flash[:notice] = 'The product has been registered'
    else
      @genres = Genre.all
      flash.now[:alert] = 'Could not register product'
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
      if @item.update(item_params)
       redirect_to admin_item_path(@item.id)
       flash[:notice] = 'Product updated'
      else
        @genres = Genre.all
        flash.now[:alert] = 'Could not update product'
        render  :edit
      end
  end

  private

  def item_params
    params.require(:item).permit(:name, :explanation, :cost, :image, :is_sales, :genre_id)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# before_action :authenticate_user!, except: [:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :telephone_number])
  end

  private

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
      # adminユーザー
      admin_root_path

    else
      # customerユーザー
      mypage_customers_path
    end
  end
  
  # def after_sign_in_path_for(resource_or_scope)
  #   root_path
  # end

  def after_sign_out_path_for(resource_or_scope) # adminかそれ以外かでサインアウトした後の遷移先画面を分岐させる
    if resource_or_scope == :admin
      new_admin_session_path

    else
      about_path

    end
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/homes/top.html.erb
<div class="container">
  <h2 class="my-5">注文履歴一覧</h2>
  <table class="table">
    <thead>
      <tr>
        <th>購入日時</th>
        <th>購入者</th>
        <th>注文個数</th>
        <th>注文ステータス</th>
      </tr>      
      <tbody>
        <% @order.each do |order| %>
          <tr>
            <td>
              <%= link_to admin_order_path(order) do%>
                <%= order.created_at.strftime("%Y-%m-%d %H:%M:%S")%>
              <% end %>
            </td>
            <td><%= order.name %></td>
            <td><%= order.order_details.count %></td>
            <td><%= order.status_i18n %></td>
          </tr>
        <% end %>
      </tbody>
    </thead>
  </table>
</div>

app/views/admin/items/edit.html.erb
<h3>商品編集</h3>

<%= form_with model: @item, url:admin_item_path do |f| %>
  
  <div>商品画像</div>
  <%= f.file_field :image, accept: "image/*" %>
  
  <div>商品名</div>
  <%= f.text_field :name %>
  
  <div>商品説明</div>
  <%= f.text_area :explanation %>
  
  <div>ジャンル</div>
  <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "--選択してください" %>
  
  <div>税抜価格</div>
  <%= f.number_field :cost, placeholder: "1000" %>円
  
  <div>
    <div>販売ステータス</div>
      <%= f.radio_button :is_sales, "true" %>
      <%= f.label :is_sales, "販売中" %>
      <%= f.radio_button :is_sales,  "false" %>
      <%= f.label :is_sales, "販売停止中" %>
  </div>
  
  
  <%= f.submit '編集' %>
  
<% end %>

app/views/admin/items/index.html.erb
<div class="container ">
  <div class="row mb-3">
    <h3>商品一覧</h3>  
    <%= link_to "+", new_admin_item_path, class: "btn rounded-circle ml-auto shadow p-2" %>
  </div>

  <table class="table  table-hover">
      <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <th>ステータス</th>
      </tr>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>  
          <td>
            <%=link_to admin_item_path(item.id) do %>
              <%= image_tag item.image, size: "100x100" %>
              <%= item.name %>
            <% end %>
          </td>
          <td>¥<%= item.add_tax_cost %></td>
          <td><%= item.genre.name %></td>
          <td>
            <% if item.is_sales == true %>
              <div>販売中</div>
            <% else %>
              <div>販売停止中</div>
            <% end %>
          </td>
        </tr>
        <% end %>
  </table>
</div>

app/views/admin/items/new.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col">
      <div class="col-6 offset-3">
        <div class="sign">
          <h3>商品新規投稿</h3>
        </div>
      
      
        <%= form_with model: @item, url:admin_items_path, method: :post do |f| %>
      
      
        <div class="my-2">商品画像</div>
        <%= f.file_field :image, accept: "image/*" %>
        
        <div class="my-2">商品名</div>
        <%= f.text_field :name %>
        
        <div class="my-2">商品説明</div>
        <%= f.text_area :explanation %>
        
        <div class="my-2">ジャンル</div>
        <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "--選択してください" %>
       
        <div class="my-2">税抜価格</div>
        <%= f.number_field :cost, placeholder: "500" %>円
        
        <div>
          <div>販売ステータス</div>
            <%= f.radio_button :is_sales, "true" %>
            <%= f.label :is_sales, "販売中" %>
            <%= f.radio_button :is_sales,  "false" %>
            <%= f.label :is_sales, "販売停止中" %>
        </div>
        
        <div class="actions my-3">
          <%= f.submit '新規登録', class: "btn btn-primary"  %>
        </div>
        
      <% end %>
      </div>
    </div>
  </div> 
</div>

app/views/admin/items/show.html.erb
<div class='container'>
<h1>商品詳細</h1>
<div class='row'>
<div class='col-md-4'>
 <%= image_tag @item.image, size: "200x200" %>
</div>

<div class='col-md-6'>
<table class="table">
  <tr>
  <td>商品名</td>
  <td><%= @item.name %></td>
  </tr>
  <tr>
  <td>商品説明</td>
  <td><%= @item.explanation %></td>
  </tr>
  <tr>
  <td>ジャンル</td>
  <td><%= @item.genre.name %></td>
  <tr>
  <td>税込価格（税抜価格）</td>
  <td><%= @item.add_tax_cost %>円</br>
      <%= @item.cost %>円
  </td>
  </tr>
  <td>販売ステータス</td>
  <td>
    <% if @item.is_sales == true %>
      <div>販売中</div>
    <% else %>
      <div>販売停止中</div>
    <% end %>
  </td>
  </tr>
</table>
</div>
</div>
</div>
<div class='text-center'>
<tr>
    <td><%= link_to "編集", edit_admin_item_path, class: 'btn btn-success' %></td>
    <td><%= link_to "一覧ページへ戻る", admin_items_path, class: "btn btn-outline-success" %></td>
  </tr>
</div>