config/routes.rb
Rails.application.routes.draw do
  get 'public/top'
  get 'public/about'
  namespace :admin do
    get 'genres/index'
    get 'genres/edit'
  end
  get 'genres/index'
  get 'genres/edit'


  namespace :admin do
    resources :items
    resources :customers
    resources :orders, except: [:index] do#今回の使用はトップページを注文一覧とするためindexを除外
      resources :order_details, only: [:update]
    end
    resources :genres
    root :to => "homes#top"
  end

  scope module: :public do

    root :to => "homes#top"
    get 'home/about' => 'homes#about', as: 'about'


    resources :addresses
    resources :items
    get 'genres/:id' => 'items#genre', as: 'genre'
    get 'orders/thanks' => 'orders#thanks'
    post 'orders/confirm' => 'orders#confirm'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :orders
    resources :cart_items
    resources :customer
    resources :customers, only: [:update] do
      collection do                                           # resourcesで定義されるアクション以外を追加する(URIにidを挟まない場合はcollection)
        get "quit"                                            # quitのルーティング
        get "mypage" => 'customers#show'                      # mypageのルーティング
        get "edit" => "customers#edit"
      end
      member do                                               # resourcesで定義されるアクション以外を追加する(URIにidを挟む場合はmember)
        patch "withdraw" => "customers#withdraw"              # 論理削除用のルーティング
      end
    end

  end

# 顧客用
# # URL /customers/sign_in ...
 devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
 devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
    # get 'addresses/inidex'
    # get 'addresses/edit'


  # namespace :public do
  #   get 'items/index'
  #   get 'items/show'

  # end
  # namespace :public do
  #   get 'orders/new'
  #   get 'orders/thanks'
  #   get 'orders/index'
  #   get 'orders/show'
  # end
  # namespace :public do
  #   get 'cart_items/index'
  # end
  # namespace :public do
  #   get 'customers/show'
  #   get 'customers/quit'
  #   get 'customers/edit'
  # end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :post_code, presence: true, length: { is: 7 }, numericality: true
  validates :address, presence: true
  validates :name, presence: true

  def post_code_in_address
    "〒" + post_code + "  " + address
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  def add_tax_cost
    (cost * 1.10).round
  end
  
  def subtotal
    item.add_tax_cost * amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :cart_items, dependent: :destroy
  # has_many :items, through: :cart_items (← customerでitemの情報を使いたいとき)
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true, uniqueness: true

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  belongs_to :genre

  validates :genre_id, presence: true
  validates :cost, presence: true
  validates :explanation, presence: true
  validates :name, presence: true
  # validates :image, presence: true

  has_one_attached :image

  def add_tax_cost
    (cost * 1.10).round
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer

  enum payment_method: {credit_card: 0, transfer: 1}
  enum address_type: { self_address: 0, registered_address: 1, new_address: 2}
	enum status: {wait_payment: 0, confirm_payment: 1, maiking: 2, prepar_shipping: 3, finish_prepar: 4}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum production_status: {unable_to_start: 0, waiting_for_production: 1, in_production: 2,  production_completed: 3}

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
   before_action :authenticate_admin!
  def top
    @order = Order.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# before_action :authenticate_user!, except: [:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :telephone_number])
  end

  private

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
      # adminユーザー
      admin_root_path

    else
      # customerユーザー
      mypage_customers_path
    end
  end
  
  # def after_sign_in_path_for(resource_or_scope)
  #   root_path
  # end

  def after_sign_out_path_for(resource_or_scope) # adminかそれ以外かでサインアウトした後の遷移先画面を分岐させる
    if resource_or_scope == :admin
      new_admin_session_path

    else
      about_path

    end
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'homes', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'customer_homes', 'data-turbolinks-track': 'reload' %>
  </head>

   <div class="navbar-fixed-top">
    <header class="shadow-sm header">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <div class="navbar-brand p-3 nagano"><%= link_to "Nagano Cake", root_path %></div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if admin_signed_in? %>
                <li class="nav-item p-2">
                  <%= link_to "商品一覧", admin_items_path, class: 'btn btn-primary' %>
                </li>
                <li class="nav-item p-2">
                  <%= link_to "会員一覧", admin_customers_path, class: "btn btn-secondary" %>
                </li>
                <li class="nav-item p-2">
                  <%= link_to "注文一覧", admin_root_path, class: "btn btn-info" %>
                  </li>
                <li class="nav-item p-2">
                  <%= link_to "ジャンル", admin_genres_index_path, class: "btn btn-warning" %>
                </li>
                <li class="nav-item p-2">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-danger" %>
                </li>
              <% elsif customer_signed_in? %>
                <div class="mt-3 mr-5 text-black">
                  ようこそ、<%= current_customer.last_name %>さん!
                </div>
                <li class="nav-item p-2">
                  <%= link_to "マイページ", mypage_customers_path, class: 'btn btn-primary' %>
                </li>
                <li class="nav-item p-2">
                  <%= link_to "商品一覧", items_path, class: "btn btn-secondary" %>
                </li>
                <li class="nav-item p-2">
                  <%= link_to "カート", cart_items_path, class: "btn btn-info" %>
                </li>
                <li class="nav-item p-2">
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-danger" %>
                </li>
              <% else %>
                <li class="nav-item p-2">
                  <%= link_to "about", about_path, class: 'btn btn-primary' %>
                </li>
                <li class="nav-item p-2">
                  <%= link_to "商品一覧", items_path, class: "btn btn-secondary" %>
                </li>
                <li class="nav-item p-2">
                  <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-info" %>
                </li>
                <li class="nav-item p-2">
                  <%= link_to "ログイン", customer_session_path, class: "btn btn-info" %>
                </li>
              <% end %>
           </ul>
          </div>
        </div>
      </nav>
    </header>
   </div>
  <body class="body">
     <% flash.each do |message_type, message| %>
      <div class="flash-message <%= message_type %>"><%= message %></div>
     <% end %>
    <%= yield %>
  </body>
</html>